### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bigsinger** [bigsinger/AndroidIdChanger#31]
- [ ] SKU: getprop **ro.boot.hardware.sku**
`
XposedHelpers.findAndHookMethod(System.class, "getProperty", String.class, new XC_MethodHook() {
      @Override
      protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
        XposedBridge.log("==== System BEFORE ==== " + param.args[0]);
      }

      @Override
      protected void afterHookedMethod(MethodHookParam param) throws Throwable {
        if (param.args[0].toString().equals("http.agent")) {
          XposedBridge.log("==== System AFTER ==== " + (String) param.getResult());
          param.setResult("Dalvik/2.1.0 (Linux; U; Android 6.0.1; Nexus 5 Build/LMY47X)");
          XposedBridge.log("==== System AFTER ==== " + (String) param.getResult());
        }
      }
    });
`
[ref](https://forum.xda-developers.com/showpost.php?p=69786196&postcount=3)

- [ ] NO HOOK VALUES:
- googlead_id
- IP
- NetType
- NetworkOperatorName
- Resolution
- Width
- SimSerialNo
- Height

- [ ] 
`
<application ...
    android:allowBackup="true">
</app>
`

- [x] Randow don't update, use 'SAVE'
- [ ] an't change ICC_ID, IP, and MNC & MCC & Operator (in some apps). Also you have cool feature to change resolution but it also not work

**Comment by bigsinger** [comment]
@lars18th  todo list is here...

**Comment by lars18th** [comment]
> @lars18th todo list is here...

OK. Thank you!

**Comment by bigsinger** [comment]
@lars18th  i get nothing  by command: getprop ro.boot.hardware.sku

**Comment by lars18th** [comment]
> @lars18th i get nothing by command: getprop ro.boot.hardware.sku

Hi,

Not all devices has this activated, only around half of them.

**Comment by lars18th** [comment]
Hi @bigsinger ,

I suggest you change the colour of the "non-already-hooked values" in the UI. For example in red (dark red) or gray. This will indicate to the users that this values isn't supported at time.

You agree?

**Comment by AdroitAdorKhan** [comment]
Can values be changed without restarting device?

**Comment by lars18th** [comment]
Hi @AdroitAdorKhan 

> Can values be changed without restarting device?

No at time. Sorry!

However, perhaps in the future... if you completly close the App that you like to hook (the code only needs to change a bit for support it).
In any case, for System Wide hooks a restart is mandatory.

Regards!

**Comment by lars18th** [comment]
Hi @bigsinger ,

Please, update the OP of this issue with other pending tasks:

- [ ]  Share "mydevice.htm" (and "hookdevice.htm") #1 #22 .

- [ ]  Import/Export of "phoneinfo.xml" and "CHANGER.xml" #4 .

- [ ]  Fix LOGs #25 .

- [ ]  Failsafe running when the module is called and the configuration is innaccesible #26 .

- [X]  Fix the RecyclerView's item "bug" when saving "phoneinfo.xml" that corrupts the saved values #29 .

This isn't a closed list, and not ordered as well. Howerver, you can use it! :smile:

**Comment by bigsinger** [comment]
It feels endless :1234: 
革命尚未成功 同志仍需努力

**Comment by lars18th** [comment]
> It feels endless 

It's only a summary of the different issues listed. You can decide in wich you like to focus.
In my opinion the bug #29 has high priority, and the second is #25. The rest are optional.
You agree?

**Comment by lars18th** [comment]
Hi @bigsinger ,

I updated my list. Futhermore, regarding the PENDING HOOK VALUES, if you like to implement for "Width", "Height" and "Resolution" (if this is the DPI value), then see this page with examples:
https://stackoverflow.com/questions/4743116/get-screen-width-and-height

I hope it helps! :smile:

**Comment by lars18th** [comment]
Hi @bigsinger ,

Regarding other pending HOOKs, they are identical to current "SimOperatorName", so:

- NetworkOperatorName: android.telephony.TelephonyManager.getNetworkOperatorName()

- NetType: android.telephony.TelephonyManager.getNetworkType()

- SimSerialNo: android.telephony.TelephonyManager.getSimSerialNumber()

See: https://developer.android.com/reference/android/telephony/TelephonyManager.html
So, I feel you can copy&paste and incorporate them.
